botanic_garden/botanic_garden/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('web.urls')),
]

botanic_garden/web/urls.py
from django.urls import path
from . import views

app_name = 'web'

urlpatterns = [
    path('index/', views.index, name='index'),
    path('plant-map/', views.plant_map, name='plant_map'),
]

botanic_garden/botanic/models.py
from django.db import models


class Family(models.Model):
    """
    Represents a botanical family.
    """
    name = models.CharField(max_length=255, unique=True, help_text="Name of the family.")
    description = models.TextField(blank=True, help_text="Description of the family.")

    def __str__(self):
        return self.name


class Genus(models.Model):
    """
    Represents a botanical genus.
    """
    name = models.CharField(max_length=255, unique=True, help_text="Name of the genus.")
    family = models.ForeignKey(Family, on_delete=models.CASCADE, help_text="Family to which the genus belongs.")
    description = models.TextField(blank=True, help_text="Description of the genus.")

    def __str__(self):
        return self.name


class Species(models.Model):
    """
    Represents a botanical species.
    """
    name = models.CharField(max_length=255, unique=True, help_text="Name of the species.")
    genus = models.ForeignKey(Genus, on_delete=models.CASCADE, help_text="Genus to which the species belongs.")
    description = models.TextField(blank=True, help_text="Description of the species.")
    blooming_season = models.CharField(max_length=50, blank=True, help_text="Blooming season of the species.")
    average_height = models.FloatField(null=True, blank=True, help_text="Average height of the species.")
    image_url = models.URLField(blank=True, help_text="URL of the representative image of the species.")
    collections = models.ManyToManyField('Collection', blank=True, help_text="Collections to which the species belongs.")

    def __str__(self):
        return self.name


class Collection(models.Model):
    """
    Represents a botanical collection.
    """
    name = models.CharField(max_length=255, unique=True, help_text="Name of the collection.")
    description = models.TextField(blank=True, help_text="Description of the collection.")

    def __str__(self):
        return self.name

botanic_garden/garden/models.py
from django.db import models
from botanic.models import Species


class Garden(models.Model):
    name = models.CharField(max_length=255)
    location = models.CharField(max_length=255)
    plants = models.ManyToManyField(Species, through='PlantLocation')

    def __str__(self):
        return self.name
    
class Event(models.Model):
    name = models.CharField(max_length=255)
    date = models.DateField()
    description = models.TextField()
    garden = models.ManyToManyField(Garden)

    def __str__(self):
        return self.name

class PlantLocation(models.Model):
    cod = models.CharField(max_length=255, unique=True)
    garden = models.ForeignKey('Garden', on_delete=models.CASCADE)
    species = models.ForeignKey(Species, on_delete=models.CASCADE)
    latitude = models.FloatField()
    longitude = models.FloatField()
    condition = models.CharField(max_length=255, blank=True, help_text="Condition of the plant at the location.")
    notes = models.TextField(blank=True, help_text="Additional notes about the plant's location.")
    image_url = models.URLField(blank=True, help_text="URL to an image of the plant at this location.")
    exsicata_image_url = models.URLField(blank=True, help_text="URL to the digitalized image of the exsicata.")
    qr_code_url = models.URLField(blank=True, help_text="URL to the QR code image or data.")

    def __str__(self):
        return f"{self.garden.name} - {self.species.name}"

botanic_garden/web/models.py
from django.db import models

# Create your models here.

botanic_garden/botanic/views.py
from django.shortcuts import render

# Create your views here.

botanic_garden/garden/views.py
from django.shortcuts import render

# Create your views here.

botanic_garden/web/views.py
from django.shortcuts import render
from garden.models import PlantLocation
from django.http import JsonResponse
from botanic.models import Family, Genus, Species
import json

def plant_map(request):
    # Recuperar parâmetros de filtro
    family_id = request.GET.get('family')
    genus_id = request.GET.get('genus')
    species_id = request.GET.get('species')

    # Recuperar dados do modelo PlantLocation com base nos filtros
    plant_locations = PlantLocation.objects.all()

    if family_id:
        plant_locations = plant_locations.filter(species__genus__family__id=family_id)
    if genus_id:
        plant_locations = plant_locations.filter(species__genus__id=genus_id)
    if species_id:
        plant_locations = plant_locations.filter(species__id=species_id)

    # Preparar os dados para o JSON
    plant_data = []
    for location in plant_locations:
        plant_data.append({
            'latitude': location.latitude,
            'longitude': location.longitude,
            'garden_name': location.garden.name,
            'species_name': location.species.name
        })

    # Convertendo os dados para JSON
    plant_data_json = json.dumps(plant_data)

    # Dados para os filtros, ordenados alfabeticamente
    families = Family.objects.all().order_by('name')
    genera = Genus.objects.all().order_by('name')
    species_list = Species.objects.all().order_by('name')

    if request.headers.get('x-requested-with') == 'XMLHttpRequest':
        return JsonResponse({'plant_data': plant_data})
    
    return render(request, 'plant_map.html', {
        'plant_data_json': plant_data_json,
        'families': families,
        'genera': genera,
        'species_list': species_list
    })




def index(request):
    return render(request, 'index.html')

botanic_garden/templates/base.html
<!-- base.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Meu Projeto Django</title>
</head>
<body>
    <header>
        <!-- Seu cabeçalho aqui -->
        <h1>Meu Projeto Django</h1>
        <nav>
            <ul>
                <!-- Outros links de navegação podem ser adicionados aqui -->
            </ul>
        </nav>
    </header>

    <main>
        {% block content %}
        <!-- O conteúdo específico da página será substituído aqui -->
        {% endblock %}
    </main>

    <footer>
        <!-- Seu rodapé aqui -->
        <p>&copy; 2024 Meu Projeto Django. Todos os direitos reservados.</p>
    </footer>
</body>
</html>

botanic_garden/templates/plant_map.html
<!-- plant_map.html -->
{% extends 'base.html' %}
{% load static %}

{% block content %}
<style>
    #map {
        position: absolute;
        top: 0;
        left: 0;
        width: 100%;
        height: 100vh;
    }
    #filterForm {
        position: absolute;
        top: 10px;
        left: 10px;
        background-color: white;
        padding: 10px;
        z-index: 1000;
        border-radius: 5px;
        box-shadow: 0px 0px 5px rgba(0, 0, 0, 0.5);
    }
</style>

<div id="filterForm">
    <form id="filter-form">
        <label for="family">Family:</label>
        <input id="family" name="family" autocomplete="off">
        
        <label for="genus">Genus:</label>
        <input id="genus" name="genus" autocomplete="off">

        <label for="species">Species:</label>
        <input id="species" name="species" autocomplete="off">

        <button type="submit">Filter</button>
    </form>
</div>

<div id="map"></div>

<script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"></script>
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">

<script>
    var map = L.map('map').setView([-18.675569, -39.862455], 17);
    L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
        maxZoom: 19,
    }).addTo(map);

    var plantIcon = L.divIcon({
        html: '<i class="fas fa-seedling" style="color: green; font-size: 24px;"></i>',
        iconSize: [24, 24],
        className: 'custom-icon'
    });

    var plantData = {{ plant_data_json|safe }};
    var markers = [];

    function updateMarkers(plantData) {
        // Remove existing markers
        markers.forEach(function(marker) {
            map.removeLayer(marker);
        });
        markers = [];

        // Add new markers
        plantData.forEach(function(plant) {
            var marker = L.marker([plant.latitude, plant.longitude], {icon: plantIcon})
                .addTo(map)
                .bindPopup(plant.garden_name + ' - ' + plant.species_name);
            markers.push(marker);
        });
    }

    updateMarkers(plantData);

    // Handle filter form submission via AJAX
    document.getElementById('filter-form').addEventListener('submit', function(event) {
        event.preventDefault();

        var formData = new FormData(this);
        var xhr = new XMLHttpRequest();
        xhr.open('GET', `{% url 'web:plant_map' %}?${new URLSearchParams(formData).toString()}`, true);
        xhr.setRequestHeader('X-Requested-With', 'XMLHttpRequest');
        xhr.onreadystatechange = function() {
            if (xhr.readyState == 4 && xhr.status == 200) {
                var response = JSON.parse(xhr.responseText);
                updateMarkers(response.plant_data);
            }
        };
        xhr.send();
    });

    // Autocomplete for Family, Genus, and Species
    $(function() {
        var families = [{% for family in families %}{ label: "{{ family.name }}", value: "{{ family.id }}" }, {% endfor %}];
        var genera = [{% for genus in genera %}{ label: "{{ genus.name }}", value: "{{ genus.id }}" }, {% endfor %}];
        var species = [{% for species in species_list %}{ label: "{{ species.name }}", value: "{{ species.id }}" }, {% endfor %}];

        $("#family").autocomplete({
            source: families,
            select: function(event, ui) {
                $("#family").val(ui.item.label);
                $("#family").data("id", ui.item.value);
            }
        });

        $("#genus").autocomplete({
            source: genera,
            select: function(event, ui) {
                $("#genus").val(ui.item.label);
                $("#genus").data("id", ui.item.value);
            }
        });

        $("#species").autocomplete({
            source: species,
            select: function(event, ui) {
                $("#species").val(ui.item.label);
                $("#species").data("id", ui.item.value);
            }
        });
    });
</script>
{% endblock %}